import "../globals.css";

import Sidebar from "./dashboard/components/sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-full overflow-hidden">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
