import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import { AuthProvider } from "@/providers/auth";
import Footer from "@/components/ui/footer";
import CartProvider from "@/providers/cart";
import Search from "@/components/ui/search";
import SearchProvider from "@/providers/search";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-full flex-col">
          <AuthProvider>
            <SearchProvider>
            <CartProvider>
              <Header />
              <Search />
              <div className="flex-1">{children}</div>
              <Footer />
            </CartProvider>
            </SearchProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
